In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from selenium.common.exceptions import StaleElementReferenceException , NoSuchElementException
import re

In [2]:
driver =webdriver.Chrome("D:\web driver\chromedriver.exe")
driver.get('https://www.flipkart.com/')

# Smartphones

In [12]:
u1=[]
s1=[]
f1=[]
sh1=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u1.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u1.append(i.get_attribute('href'))
time.sleep(5)

for i in u1:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s1.append(j.text)
            
    except NoSuchElementException:
        s1.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh1.append(k.text)
            
    except NoSuchElementException:
        sh1.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f1.append(l.text)
            
    except NoSuchElementException:
        f1.append('-')
            
    
time.sleep(2)   

# Make dataframe
df = pd.DataFrame({'Star Ratings':s1,'Short Review':sh1,'Full Review':f1})

df

,Star Ratings,Short Review,Full Review
0,-,-,-
1,-,-,-
2,5,Brilliant,Good phone at this price point\nCamera is by f...
3,-,-,-
4,5,Excellent,I have been useing this device for 20 days.......
...,...,...,...
985,5,Mind-blowing purchase,"Camera Nice , Battery very good,look wise also..."
986,-,-,-
987,-,-,-
988,5,Highly recommended,"This phone is just wow, absolutely a best phon..."
989,5,Just wow!,It's a wonderful handset in this range ...just...

In [13]:
# saving the dataframe

df.to_csv('smartphone.csv')

In [15]:
u1=[]
s1=[]
f1=[]
sh1=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u1.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u1.append(i.get_attribute('href'))
time.sleep(5)

for i in u1:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s1.append(j.text)
            
    except NoSuchElementException:
        s1.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh1.append(k.text)
            
    except NoSuchElementException:
        sh1.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f1.append(l.text)
            
    except NoSuchElementException:
        f1.append('-')
            
    
time.sleep(2)    

# Make dataframe
df = pd.DataFrame({'Star Ratings':s1,'Short Review':sh1,'Full Review':f1})

df

,Star Ratings,Short Review,Full Review
0,-,-,-
1,5,Perfect product!,Will be honest running an A13 beta and will su...
2,5,Just wow!,It's a great deal.....battery back up and scre...
3,-,-,-
4,-,-,-
...,...,...,...
985,-,-,-
986,5,Perfect product!,Camera details are perfect and night mode work...
987,-,-,-
988,5,Simply awesome,Excellent touch response nice performance good...
989,5,Excellent,"If u want a compact phone, go for it!\nBattery..."

In [21]:
# saving the dataframe

df.to_csv('smartphone_1.csv')

In [3]:
u1=[]
s1=[]
f1=[]
sh1=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u1.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u1.append(i.get_attribute('href'))
time.sleep(5)

for i in u1:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s1.append(j.text)
            
    except NoSuchElementException:
        s1.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh1.append(k.text)
            
    except NoSuchElementException:
        sh1.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f1.append(l.text)
            
    except NoSuchElementException:
        f1.append('-')
            
    
time.sleep(2)   

# Make dataframe
df = pd.DataFrame({'Star Ratings':s1,'Short Review':sh1,'Full Review':f1})

df

,Star Ratings,Short Review,Full Review
0,5,Perfect product!,Camera details are perfect and night mode work...
1,5,Mind-blowing purchase,nice design camera quality good battery back u...
2,5,Could be way better,Nothing is great and not worth for money what ...
3,4,Worth the money,Writing this after 1 day use -\nBATTERY - 5/5 ...
4,5,Terrific purchase,"Firstly, Thanks to realme for this amazing all..."
...,...,...,...
985,5,Just wow!,It's a wonderful handset in this range ...just...
986,4,Delightful,It is a good phone according to the amount of ...
987,5,Simply awesome,Excellent touch response nice performance good...
988,4,Wonderful,Good product and it's performance
989,4,Delightful,Using this phone after using many phone and ho...

In [4]:
df.to_csv('smartphone_2.csv')

# Smartwatches

In [22]:
u2=[]
s2=[]
f2=[]
sh2=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u2.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u2.append(i.get_attribute('href'))
time.sleep(5)

for i in u2:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s2.append(j.text)
            
    except NoSuchElementException:
        s2.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh2.append(k.text)
            
    except NoSuchElementException:
        sh2.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f2.append(l.text)
            
    except NoSuchElementException:
        f2.append('-')
            
    
time.sleep(2)    

# Make dataframe
df2 = pd.DataFrame({'Star Ratings':s2,'Short Review':sh2,'Full Review':f2})

df2

,Star Ratings,Short Review,Full Review
0,5,Mind-blowing purchase,"Very good product, quality best in price..👍👍ca..."
1,5,Excellent,I have been useing this device for 20 days.......
2,5,Just wow!,It's a wonderful handset in this range ...just...
3,5,Just wow!,It's a great deal.....battery back up and scre...
4,-,-,-
...,...,...,...
985,-,-,-
986,3,Fair,"Overall decent phone for lowrange price, what ..."
987,5,Simply awesome,Excellent touch response nice performance good...
988,4,Delightful,Overall good phone\nPros\nSmooth display\nCall...
989,-,-,-

In [23]:
df2.to_csv('smartwatch.csv')

In [24]:
u2=[]
s2=[]
f2=[]
sh2=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u2.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u2.append(i.get_attribute('href'))
time.sleep(5)

for i in u2:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s2.append(j.text)
            
    except NoSuchElementException:
        s2.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh2.append(k.text)
            
    except NoSuchElementException:
        sh2.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f2.append(l.text)
            
    except NoSuchElementException:
        f2.append('-')
            
    
time.sleep(2)    

# Make dataframe
df2 = pd.DataFrame({'Star Ratings':s2,'Short Review':sh2,'Full Review':f2})

df2

,Star Ratings,Short Review,Full Review
0,5,Mind-blowing purchase,"Very good product, quality best in price..👍👍ca..."
1,5,Excellent,I have been useing this device for 20 days.......
2,5,Just wow!,It's a great deal.....battery back up and scre...
3,4,Really Nice,I purchased this phone as soon as it was launc...
4,5,Wonderful,I am very happy to buy it awesome 👍 mobile and...
...,...,...,...
985,5,Could be way better,Nothing is great and not worth for money what ...
986,3,Fair,"Overall decent phone for lowrange price, what ..."
987,5,Wonderful,Very good product in this range i am fully sat...
988,-,-,-
989,4,Delightful,A Midrange phone from OnePlus.\nWhy I choose t...

In [25]:
df2.to_csv('smartwatch_1.csv')

In [5]:
u2=[]
s2=[]
f2=[]
sh2=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u2.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u2.append(i.get_attribute('href'))
time.sleep(5)

for i in u2:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s2.append(j.text)
            
    except NoSuchElementException:
        s2.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh2.append(k.text)
            
    except NoSuchElementException:
        sh2.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f2.append(l.text)
            
    except NoSuchElementException:
        f2.append('-')
            
    
time.sleep(2)    

# Make dataframe
df2 = pd.DataFrame({'Star Ratings':s2,'Short Review':sh2,'Full Review':f2})

df2

,Star Ratings,Short Review,Full Review
0,5,Perfect product!,Camera details are perfect and night mode work...
1,5,Wonderful,Very good mobile value for money back camera i...
2,4,Could be way better,Nothing is great and not worth for money what ...
3,5,Simply awesome,Excellent value-for-money device with plenty o...
4,5,Mind-blowing purchase,"Very good product, quality best in price..👍👍ca..."
...,...,...,...
985,-,-,-
986,4,Delightful,It is a good phone according to the amount of ...
987,5,Simply awesome,Excellent touch response nice performance good...
988,5,Wonderful,Worth for money\nSuper camera\nVery good batte...
989,5,Great product,Best phone 5 star best for gaming and video\nB...

In [6]:
df2.to_csv('smartwatch_2.csv')

# Laptops

In [6]:
u3=[]
s3=[]
f3=[]
sh3=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u3.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u3.append(i.get_attribute('href'))
time.sleep(5)

for i in u3:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s3.append(j.text)
            
    except NoSuchElementException:
        s3.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh3.append(k.text)
            
    except NoSuchElementException:
        sh3.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f3.append(l.text)
            
    except NoSuchElementException:
        f3.append('-')
            
    
time.sleep(2)    

# Make dataframe
df3 = pd.DataFrame({'Star Ratings':s3,'Short Review':sh3,'Full Review':f3})

df3

,Star Ratings,Short Review,Full Review
0,4,Wonderful,I have used this laptop for one week and my ob...
1,5,Just wow!,Killer laptop at its price range. Beautiful st...
2,5,Best in the market!,It's been 2 weeks and bought it in ~67K. You w...
3,-,-,-
4,5,Best in the market!,Product is very good.\nSound quality is very g...
...,...,...,...
985,5,Worth every penny,Best laptop 💻 . I loved it . Don't hesitate to...
986,4,Really Nice,A superb product\nIT'S SPEED ! WOW. amazing\nB...
987,-,-,-
988,4,Really Nice,A superb product\nIT'S SPEED ! WOW. amazing\nB...
989,4,Really Nice,A superb product\nIT'S SPEED ! WOW. amazing\nB...

In [7]:
df3.to_csv('laptop.csv')

In [3]:
u3=[]
s3=[]
f3=[]
sh3=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u3.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u3.append(i.get_attribute('href'))
time.sleep(5)

for i in u3:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s3.append(j.text)
            
    except NoSuchElementException:
        s3.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh3.append(k.text)
            
    except NoSuchElementException:
        sh3.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f3.append(l.text)
            
    except NoSuchElementException:
        f3.append('-')
            
    
time.sleep(2)    

# Make dataframe
df3 = pd.DataFrame({'Star Ratings':s3,'Short Review':sh3,'Full Review':f3})

df3

,Star Ratings,Short Review,Full Review
0,-,-,-
1,5,Highly recommended,Very stylish and slim design . System speed is...
2,-,-,-
3,5,Simply awesome,Very impressive design with thin and light wei...
4,5,Must buy!,It is best hard and heavy machine for gamers a...
...,...,...,...
985,5,Fabulous!,Superb product.\nBest ever product in this pri...
986,5,Great product,I am a officer going person who need a laptop ...
987,5,Simply awesome,Processor is very awesome and good product .an...
988,4,Good quality product,Pros _-_\nIts fast due to samsung ssd around (...
989,4,Nice product,"Looks are good, processing is fast, screen is ..."

In [4]:
df3.to_csv('laptop_1.csv')

# Headphones

In [9]:
u4=[]
s4=[]
f4=[]
s4=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u4.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u4.append(i.get_attribute('href'))
time.sleep(5)

for i in u4:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s4.append(j.text)
            
    except NoSuchElementException:
        s4.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh4.append(k.text)
            
    except NoSuchElementException:
        sh4.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f4.append(l.text)
            
    except NoSuchElementException:
        f4.append('-')
            
    
time.sleep(2)    

# Make dataframe
df4 = pd.DataFrame({'Star Ratings':s4,'Short Review':sh4,'Full Review':f4})

df4

,Star Ratings,Short Review,Full Review
0,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
1,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
2,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
3,5,Best in the market!,Hello guys i am writing this review after 5 da...
4,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
...,...,...,...
985,5,Must buy!,I'M GIVING REVIEW AFTER 26 DAY OF USE.\nWHEN I...
986,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
987,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
988,5,Super!,Bass quality is awesome...great for bass lover...
989,5,Excellent,The delivery was super fast......\n\nSo writin...

In [10]:
df4.to_csv('headphone.csv')

In [11]:
u4=[]
s4=[]
f4=[]
sh4=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u4.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u4.append(i.get_attribute('href'))
time.sleep(5)

for i in u4:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s4.append(j.text)
            
    except NoSuchElementException:
        s4.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh4.append(k.text)
            
    except NoSuchElementException:
        sh4.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f4.append(l.text)
            
    except NoSuchElementException:
        f4.append('-')
            
    
time.sleep(2)    

# Make dataframe
df4 = pd.DataFrame({'Star Ratings':s4,'Short Review':sh4,'Full Review':f4})

df4

,Star Ratings,Short Review,Full Review
0,5,Excellent,The delivery was super fast......\n\nSo writin...
1,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
2,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
3,-,-,-
4,5,Super!,Bass quality is awesome...great for bass lover...
...,...,...,...
985,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
986,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
987,-,-,-
988,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
989,5,Excellent,The delivery was super fast......\n\nSo writin...

In [12]:
df4.to_csv('headphone_1.csv')

In [5]:
u4=[]
s4=[]
f4=[]
sh4=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u4.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u4.append(i.get_attribute('href'))
time.sleep(5)

for i in u4:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s4.append(j.text)
            
    except NoSuchElementException:
        s4.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh4.append(k.text)
            
    except NoSuchElementException:
        sh4.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f4.append(l.text)
            
    except NoSuchElementException:
        f4.append('-')
            
    
time.sleep(2)    

# Make dataframe
df4 = pd.DataFrame({'Star Ratings':s4,'Short Review':sh4,'Full Review':f4})

df4

,Star Ratings,Short Review,Full Review
0,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
1,-,-,-
2,-,-,-
3,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
4,5,Perfect product!,It is very good product I love this Bluetooth ...
...,...,...,...
985,5,Worst experience ever!,Sound quality is so much different than realme...
986,-,-,-
987,-,-,-
988,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...
989,5,Classy product,Boult ProBass vs BoAt reckerz 225 - I have use...

In [6]:
df4.to_csv('headphone_2.csv')

## Printer

In [3]:
u5=[]
s5=[]
f5=[]
sh5=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u5.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u5.append(i.get_attribute('href'))
time.sleep(5)

for i in u5:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s5.append(j.text)
            
    except NoSuchElementException:
        s5.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh5.append(k.text)
            
    except NoSuchElementException:
        sh5.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f5.append(l.text)
            
    except NoSuchElementException:
        f5.append('-')
            
    
time.sleep(2)    

# Make dataframe
df5 = pd.DataFrame({'Star Ratings':s5,'Short Review':sh5,'Full Review':f5})

df5

,Star Ratings,Short Review,Full Review
0,-,-,-
1,5,Brilliant,Print quality in awasome and easily id photo c...
2,-,-,-
3,5,Brilliant,Print quality in awasome and easily id photo c...
4,5,Brilliant,Print quality in awasome and easily id photo c...
...,...,...,...
985,-,-,-
986,-,-,-
987,5,Brilliant,Print quality in awasome and easily id photo c...
988,-,-,-
989,5,Brilliant,Print quality in awasome and easily id photo c...

In [4]:
df5.to_csv('printer.csv')

# professional camera

In [15]:
u6=[]
s6=[]
f6=[]
sh6=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u6.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u6.append(i.get_attribute('href'))
time.sleep(5)

for i in u6:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s6.append(j.text)
            
    except NoSuchElementException:
        s6.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh6.append(k.text)
            
    except NoSuchElementException:
        sh6.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f6.append(l.text)
            
    except NoSuchElementException:
        f6.append('-')
            
    
time.sleep(2)    

# Make dataframe
df6 = pd.DataFrame({'Star Ratings':s6,'Short Review':sh6,'Full Review':f6})

df6

,Star Ratings,Short Review,Full Review
0,-,-,-
1,4,Utterly Disappointed,Not good don't buy
2,5,Best in the market!,wow wow wow....as expected with this you shoul...
3,5,Just wow!,Amazing Product with new features like Selfie....
4,5,Very poor,Not multy propse only selfi stick
...,...,...,...
985,-,-,-
986,4,Good quality product,good one. picture quality is good. WiFi works ...
987,5,Worth every penny,The very good product the picture of the camer...
988,-,-,-
989,5,Very poor,Worsted product

In [16]:
df6.to_csv('camera.csv')

In [17]:
u6=[]
s6=[]
f6=[]
sh6=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u6.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u6.append(i.get_attribute('href'))
time.sleep(5)

for i in u6:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s6.append(j.text)
            
    except NoSuchElementException:
        s6.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh6.append(k.text)
            
    except NoSuchElementException:
        sh6.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f6.append(l.text)
            
    except NoSuchElementException:
        f6.append('-')
            
    
time.sleep(2)    

# Make dataframe
df6 = pd.DataFrame({'Star Ratings':s6,'Short Review':sh6,'Full Review':f6})

df6

,Star Ratings,Short Review,Full Review
0,-,-,-
1,5,Horrible,Its not support with device
2,-,-,-
3,5,Worth every penny,The very good product the picture of the camer...
4,5,Excellent,So pretty and value for money
...,...,...,...
985,5,Classy product,best camera ever created in APS-C sensor
986,-,-,-
987,-,-,-
988,-,-,-
989,5,Super!,Week one review: As praised and revered by pro...

In [18]:
df6.to_csv('camera_1.csv')

# Monitors

In [19]:
u7=[]
s7=[]
f7=[]
sh7=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u7.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u7.append(i.get_attribute('href'))
time.sleep(5)

for i in u7:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s7.append(j.text)
            
    except NoSuchElementException:
        s7.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh7.append(k.text)
            
    except NoSuchElementException:
        sh7.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f7.append(l.text)
            
    except NoSuchElementException:
        f7.append('-')
            
    
time.sleep(2)    

# Make dataframe
df7 = pd.DataFrame({'Star Ratings':s7,'Short Review':sh7,'Full Review':f7})

df7

,Star Ratings,Short Review,Full Review
0,5,Not good,Picture quality is very poor ...
1,-,-,-
2,5,Fabulous!,I have bought this for my office WFH setup. Lo...
3,5,Best in the market!,Good prodect for the value and gaming using fo...
4,5,Utterly Disappointed,So bad picture quality and looking like cheap ...
...,...,...,...
985,3,Just okay,Only one I can tell\nPicture quality was not c...
986,-,-,-
987,5,Perfect product!,Excellent monitor if you are looking for offic...
988,4,Slightly disappointed,Nice product...trust worthy
989,5,Awesome,It's a good choice if you constantly switch be...

In [20]:
df7.to_csv('monitor.csv')

In [21]:
u7=[]
s7=[]
f7=[]
sh7=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u7.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u7.append(i.get_attribute('href'))
time.sleep(5)

for i in u7:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s7.append(j.text)
            
    except NoSuchElementException:
        s7.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh7.append(k.text)
            
    except NoSuchElementException:
        sh7.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f7.append(l.text)
            
    except NoSuchElementException:
        f7.append('-')
            
    
time.sleep(2)    

# Make dataframe
df7 = pd.DataFrame({'Star Ratings':s7,'Short Review':sh7,'Full Review':f7})

df7

,Star Ratings,Short Review,Full Review
0,5,Awesome,It's a good choice if you constantly switch be...
1,3,Just okay,Only one I can tell\nPicture quality was not c...
2,4,Pretty good,It's amazing really super in budget impressive
3,5,Perfect product!,Excellent monitor if you are looking for offic...
4,4,Slightly disappointed,Nice product...trust worthy
...,...,...,...
985,5,Just wow!,Nice product I love all the features but the b...
986,5,Highly recommended,Great deal really worth buying.
987,4,Great fro the price and good color and picture...,"Got it today after long delay, but happy with ..."
988,5,Fabulous!,"Good one, worth for the price"
989,3,Just okay,This monitor is good but it's small

In [22]:
df7.to_csv('monitor_1.csv')

# Home theater

In [23]:
u8=[]
s8=[]
f8=[]
sh8=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u8.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u8.append(i.get_attribute('href'))
time.sleep(5)

for i in u8:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s8.append(j.text)
            
    except NoSuchElementException:
        s8.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh8.append(k.text)
            
    except NoSuchElementException:
        sh8.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f8.append(l.text)
            
    except NoSuchElementException:
        f8.append('-')
            
    
time.sleep(2)    

# Make dataframe
df8 = pd.DataFrame({'Star Ratings':s8,'Short Review':sh8,'Full Review':f8})

df8

,Star Ratings,Short Review,Full Review
0,5,Awesome,Superb Design & Awesome Sound Quality..
1,5,Awesome,Superb Design & Awesome Sound Quality..
2,5,Awesome,Superb Design & Awesome Sound Quality..
3,5,Great product,"The quality is genuine, high quality sound and..."
4,5,Very poor,So bad product in my life light is good but vo...
...,...,...,...
985,5,Wonderful,Very nice product in your budget 👍👍
986,5,Must buy!,Its a vintage looking speaker with good batter...
987,5,Awesome,Superb Design & Awesome Sound Quality..
988,-,-,-
989,5,Amazing speaker creative T6300 but prices are ...,Really good sounding speakers creative T6300 5...

In [24]:
df8.to_csv('home_theater.csv')

In [25]:
u8=[]
s8=[]
f8=[]
sh8=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u8.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u8.append(i.get_attribute('href'))
time.sleep(5)

for i in u8:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s8.append(j.text)
            
    except NoSuchElementException:
        s8.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh8.append(k.text)
            
    except NoSuchElementException:
        sh8.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f8.append(l.text)
            
    except NoSuchElementException:
        f8.append('-')
            
    
time.sleep(2)    

# Make dataframe
df8 = pd.DataFrame({'Star Ratings':s8,'Short Review':sh8,'Full Review':f8})

df8

,Star Ratings,Short Review,Full Review
0,5,Amazing speaker creative T6300 but prices are ...,Really good sounding speakers creative T6300 5...
1,5,Wonderful,Very nice product in your budget 👍👍
2,5,Must buy!,Its a vintage looking speaker with good batter...
3,5,Awesome,Superb Design & Awesome Sound Quality..
4,5,Excellent,"Cool speakers, nice design, good sound.\nOvera..."
...,...,...,...
985,5,Awesome,Superb Design & Awesome Sound Quality..
986,5,Awesome,Superb Design & Awesome Sound Quality..
987,5,Bad quality,Metrial pastic but\nvalue money
988,5,Waste of money!,Repeatable songs. Non refundable item. Big in ...
989,5,Slightly disappointed,Bluetooth connectivity problem\nBass Speaker b...

In [4]:
df8.to_csv('home_theater_1.csv')

In [3]:
u8=[]
s8=[]
f8=[]
sh8=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u8.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u8.append(i.get_attribute('href'))
time.sleep(5)

for i in u8:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s8.append(j.text)
            
    except NoSuchElementException:
        s8.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh8.append(k.text)
            
    except NoSuchElementException:
        sh8.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f8.append(l.text)
            
    except NoSuchElementException:
        f8.append('-')
            
    
time.sleep(2)    

# Make dataframe
df8= pd.DataFrame({'Star Ratings':s8,'Short Review':sh8,'Full Review':f8})

df8

,Star Ratings,Short Review,Full Review
0,5,Worth every penny,Good. But Treble is less. Good for 80s & 90s H...
1,5,Awesome,Superb Design & Awesome Sound Quality..
2,5,Great product,"The quality is genuine, high quality sound and..."
3,5,Terrific purchase,osm nice 👍👍 this home theater is so good this ...
4,5,Absolute rubbish!,The mike for karaoke with this speaker is a wa...
...,...,...,...
985,5,Awesome,Superb Design & Awesome Sound Quality..
986,5,Wonderful,Very nice product in your budget 👍👍
987,5,Awesome,Superb Design & Awesome Sound Quality..
988,5,Awesome,Superb Design & Awesome Sound Quality..
989,5,Awesome,Superb Design & Awesome Sound Quality..

In [5]:
df8.to_csv('home_theater_2.csv')

# Router

In [6]:
u9=[]
s9=[]
f9=[]
sh9=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u9.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u9.append(i.get_attribute('href'))
time.sleep(5)

for i in u9:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s9.append(j.text)
            
    except NoSuchElementException:
        s9.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh9.append(k.text)
            
    except NoSuchElementException:
        sh9.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f9.append(l.text)
            
    except NoSuchElementException:
        f9.append('-')
            
    
time.sleep(2)    

# Make dataframe
df9 = pd.DataFrame({'Star Ratings':s9,'Short Review':sh9,'Full Review':f9})

df9

,Star Ratings,Short Review,Full Review
0,5,Mind-blowing purchase,Undoubtedly awesome product. I purchased it wi...
1,5,Wonderful,This is just splendid. Does a great job at han...
2,3,Does the job,Good
3,5,Classy product,Fastest delivery good thanks
4,3,Very poor,In it's youtube review unit it has many featur...
...,...,...,...
985,5,Best in the market!,This is very important for cctv DVR online\nIt...
986,3,Does the job,Good
987,5,Worst experience ever!,"Built quality is very cheap, wifi range is ver..."
988,4,Nice product,I am using this router from yesterday it worki...
989,3,Does the job,Good

In [7]:
df9.to_csv('router.csv')

In [8]:
u9=[]
s9=[]
f9=[]
sh9=[]
time.sleep(2)
start=1
end=100

for page in range(start,end):
    url_1 = driver.find_elements_by_xpath('//a[@class="ge-49M _2Kfbh8"]')
    for i in url_1:
        u9.append(i.get_attribute('href'))
        
    url_2 =  driver.find_elements_by_xpath('//a[@class="ge-49M"]')
    for i in url_2:
        u9.append(i.get_attribute('href'))
time.sleep(5)

for i in u9:
    driver.get(i)
    time.sleep(2)
    
    
    try:
        j = driver.find_element_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
        s9.append(j.text)
            
    except NoSuchElementException:
        stzss.append('-')
        
        
    time.sleep(1)   
    
    try:
        k = driver.find_element_by_xpath('//p[@ class="_2-N8zT"]')
        sh9.append(k.text)
            
    except NoSuchElementException:
        sh9.append('-')
        
    time.sleep(1)    
    
    try:
        l = driver.find_element_by_xpath('//div[@class="t-ZTKy"]/div/div')
        f9.append(l.text)
            
    except NoSuchElementException:
        f9.append('-')
            
    
time.sleep(2)    

# Make dataframe
df9 = pd.DataFrame({'Star Ratings':s9,'Short Review':sh9,'Full Review':f9})

df9

,Star Ratings,Short Review,Full Review
0,3,Does the job,Good
1,5,Best in the market!,This is very important for cctv DVR online\nIt...
2,3,Does the job,Good
3,5,Worst experience ever!,"Built quality is very cheap, wifi range is ver..."
4,4,Nice product,I am using this router from yesterday it worki...
...,...,...,...
985,3,Does the job,Good
986,3,Does the job,Good
987,3,Does the job,Good
988,5,Excellent router and amazing AC wireless speed,This is my first AC wireless router and I am v...
989,5,Great product,Very perfect working is very fine only need to...

In [9]:
df9.to_csv('router1.csv')